### ISSUE TITLE
become an astropy affiliated package

### ISSUE THREAD

**Issue by lspitler** [AstroHuntsman/gunagala#42]
Aim is to become an affiliated package. Need to accomplish the following:

- [ ] improve user experience to create custom instruments and PSFs e.g. #8 #1 #2 
- [ ] ensure use of existing astropy packages by fixing a few depreciation warnings and out of date dependencies #30 #43
- [ ] adopt astropy base package template (almost done) and help determine best workflow for maintenance (e.g. release schedule) #38 #40 
- [ ] provide key useful features: analytical PSF memory error fix #29 ; implement spatially-varying PSF #23 PSF wings #21 physically motivated PSF #4

**Comment by lspitler** [comment]
@gbpoole this Issue summarises the set of Technical issues that we would like help with via the ADACS MAP.
